// <auto-generated />
using System;
using Bolstra.Api.Models;
using Bolstra.Api.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Internal;

namespace Bolstra.Migrations
{
    [DbContext(typeof(BolstraDb))]
    [Migration("20181024200300_BostraDB-InitialCreating")]
    partial class BostraDBInitialCreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            var x = typeof(object).GetMethod(nameof(object.ToString), Type.EmptyTypes).DisplayName();
        }
    }
}
